### PR TITLE
Edits applied

### PR DESCRIPTION
**Pull request by andrewryh**
Closing issue #2

### CODE REVIEW

**Comment by jbae11** [comment]
Couple of comments:
1. There's an image blocking text at slide 9
2. Slide 9 title could be `Challenges in simulating MSR`
3. Slide 10: goals could be actions, like `Develop a tool for online-reprocessing...` , or I think a better goal would be just `Online reprocessing depletion calculation`. Same goes for goal 2
4. Slide 16 `poisons` could be elaborated (list of isotopes)

I think in the perspective of the audience (non-nuclear engineers), it should be stressed how much computing power one needs to do Monte Carlo simulation on a reactor core, multiple times. That being said, I think there's little mention into SERPENT, which is the actual depletion part that requires most of the computing power.

**Comment by katyhuff** [comment]
I think you need to gitignore the minted directory (or, stop using `git add *` and `git add .`)

**Comment by katyhuff** [comment]
`acknowledgements.tex~` has a file extension like a temp file.

**Comment by katyhuff** [comment]
Looks good other than a couple of unnecessary new files. I added some text to the acks. Not sure if that text fits on the slide.

**Review by katyhuff — CHANGES_REQUESTED** [review]
remove _minted/* and acknowledgements.tex~

**Comment by andrewryh** [comment]
Thanks for the feedback, I have removed these files/folder

**Pull request merged**
